# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_auto_20171016_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
