# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 20:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_marker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='link',
            field=models.TextField(default=0, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
