# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_marker_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('iconType', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
