# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0005_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapapp.Icon'),
        ),
    ]
