# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 15:14
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0007_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='link',
        ),
        migrations.AlterField(
            model_name='marker',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='49.842728, 24.025021', max_length=63),
        ),
    ]
